-- جدول الكتب الرقمية
CREATE TABLE IF NOT EXISTS digital_books (
    digital_book_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    book_number VARCHAR(50) UNIQUE,
    book_title VARCHAR(255) NOT NULL,
    book_description TEXT,
    department_id INT UNSIGNED,
    cover_image VARCHAR(500) NULL,
    file_path VARCHAR(500) NULL,
    file_type ENUM('pdf', 'doc', 'docx', 'ppt', 'pptx') DEFAULT 'pdf',
    file_size INT UNSIGNED DEFAULT 0,
    author VARCHAR(255),
    publisher VARCHAR(255),
    publish_year INT,
    isbn VARCHAR(50),
    language VARCHAR(50) DEFAULT 'عربي',
    access_type ENUM('internal', 'external', 'both') DEFAULT 'internal',
    license_type VARCHAR(100),
    is_active TINYINT(1) DEFAULT 1,
    downloads_count INT UNSIGNED DEFAULT 0,
    views_count INT UNSIGNED DEFAULT 0,
    created_by INT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(department_id) ON DELETE SET NULL,
    INDEX idx_number (book_number),
    INDEX idx_title (book_title),
    INDEX idx_department (department_id),
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
